# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

topological_hypervolume <- function(data, dist_barycenter, dist_sparsify) {
    .Call(`_tpaw_topological_hypervolume`, data, dist_barycenter, dist_sparsify)
}

