# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hypervolume_t <- function(data, dist_barycenter, dist_sparsify) {
    .Call(`_hvt_hypervolume_t`, data, dist_barycenter, dist_sparsify)
}

